import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Moon,Carrot,PersonSimpleWalk,DeviceMobile,BookOpen,ArrowRight,ArrowLeft,Check,House,ClockCounterClockwise,Plant,X,Timer,Sun,CheckCircle,ArrowUpRight,Heart,Leaf} from '@phosphor-icons/react';
import {behaviors,nodes,statusText,type Behavior,type Status,type Action} from './data';
import {load,persist,aggregate,actionList,createRecord,feedback,adjusted,clearStorage,remaining,createCustomMethod,type CustomMethod,type Draft,type RecordItem} from './model';
import './styles.css';
const icons={sleep:Moon,food:Carrot,move:PersonSimpleWalk,phone:DeviceMobile,task:BookOpen};
const initial=load();
const date=(s:string)=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s));
function App(){
const [history,setHistory]=useState(initial.history),[draft,setDraft]=useState<Draft|undefined>(initial.draft),[route,setRoute]=useState(location.hash.slice(1)||'home'),[error,setError]=useState(initial.error),[review,setReview]=useState(false),[feedbackStatus,setFeedbackStatus]=useState<Status>(),[clear,setClear]=useState(false),[expanded,setExpanded]=useState<string>(),[now,setNow]=useState(Date.now());
const [firstVisit,setFirstVisit]=useState(initial.firstVisit);
const [methods,setMethods]=useState(initial.methods),[customOpen,setCustomOpen]=useState(false),[customError,setCustomError]=useState(''),[methodTab,setMethodTab]=useState<'created'|'effective'>('created');
const lock=useRef(false);const top=useRef<HTMLElement>(null);
useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(1)||'home');setFeedbackStatus(undefined);lock.current=false};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
useEffect(()=>{const e=persist(history,draft,firstVisit,methods);if(e)setError(e)},[history,draft,firstVisit,methods]);
useEffect(()=>{window.scrollTo(0,0);top.current?.focus({preventScroll:true});lock.current=false},[route,draft?.nodeId,draft?.stage]);
useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
const go=(to:string)=>{setRoute(to);location.hash=to;setFeedbackStatus(undefined);setCustomOpen(false);setCustomError('')};
const start=(b:Behavior,when:'now'|'past'='now',parent?:string)=>{setDraft({behavior:b,when,trail:[],nodeId:b,stage:'question',parent});go('flow');setReview(false)};
const allStrategies=aggregate(history),effective=allStrategies.filter(s=>s.status==='effective');
const waiting=[...history].reverse().filter(h=>h.status==='WAITING');
const current=history.find(h=>h.id===route.split('/')[1]);
const activeFeedback=route.startsWith('adjust/')?current?.status:feedbackStatus;
const flow=route==='flow'&&draft, node=flow?nodes[draft.nodeId]:undefined;
const patch=(p:Partial<Draft>)=>setDraft(d=>d?{...d,...p}:d);
const choose=(label:string,to:string)=>{if(!draft)return;const n=nodes[to];patch({trail:[...draft.trail,{id:draft.nodeId,label}],nodeId:to,stage:n.reason?'reason':'question',action:undefined})};
const back=()=>{if(!draft)return;if(draft.stage==='commit'){patch({stage:'strategy',action:undefined});return}if(draft.stage==='strategy'){patch({stage:'reason',action:undefined});return}const trail=[...draft.trail];const prev=trail.pop();if(prev)patch({trail,nodeId:prev.id,stage:'question',action:undefined,noShortcut:false});else go('home')};
const commit=()=>{
 if(!draft?.action||lock.current)return;lock.current=true;
 try {const h=createRecord(draft);setHistory(prev=>[...prev,h]);
  if(h.action.origin==='custom')setMethods(prev=>prev.some(m=>m.code===h.action.code&&m.action.version===h.action.version)?prev:[...prev,{code:h.action.code,createdAt:h.createdAt,behavior:h.behavior,reason_code:h.reason_code,reasonLabel:h.reasonLabel,action:h.action}]);
  setDraft(undefined);go(`done/${h.id}`);
 }catch(e){lock.current=false;setError(e instanceof Error?e.message:'这次没能保存，请再试一次。')}
};
const saveMethod=(event:React.FormEvent)=>{
 event.preventDefault();if(!draft)return;
 try {const title=draft.customText||'';const minutes=draft.customMinutes?.trim()?Number(draft.customMinutes):undefined;
  const existing=methods.find(m=>m.behavior===draft.behavior&&m.reason_code===draft.nodeId&&m.action.title===title.trim()&&m.action.minutes===minutes);
  const method=existing||createCustomMethod(draft,title,minutes);
  if(!existing)setMethods(prev=>[...prev,method]);
  patch({action:method.action,stage:'commit',customText:undefined,customMinutes:undefined});setCustomOpen(false);setCustomError('');
 }catch(e){setCustomError(e instanceof Error?e.message:'请检查填写的内容。')}
};
const useMethod=(m:Pick<CustomMethod,'behavior'|'reason_code'|'action'>)=>{setDraft({behavior:m.behavior,when:'now',trail:[{id:m.behavior,label:nodes[m.reason_code].reason!.label}],nodeId:m.reason_code,stage:'commit',action:m.action});go('flow')};
const submitRating=(h:RecordItem,status:Status)=>{if(lock.current||h.status!=='WAITING')return;lock.current=true;setHistory(prev=>feedback(prev,h.id,status));go(`done/${h.id}`)};
const updateFeedback=(h:RecordItem,s:Status,code?:string)=>setHistory(prev=>prev.map(item=>item.id===h.id&&item.status===s?{...item,feedback_code:code}:item));
const resolve=(h:RecordItem,s:Status,code:string)=>{if(lock.current)return;lock.current=true;updateFeedback(h,s,code);if(s==='WORKED'){go(`done/${h.id}`);return}if(code==='different'||s==='FAILED'||code==='unsuitable'){start(h.behavior,h.when,h.id);return}setDraft({behavior:h.behavior,when:h.when,trail:h.trail||[{id:h.behavior,label:h.situation_code}],nodeId:h.reason_code,stage:'strategy',parent:h.id,adjustment:code,noShortcut:true});go('flow')};
const reuse=(h:RecordItem)=>{setDraft({behavior:h.behavior,when:'now',trail:[{id:h.behavior,label:h.situation_code}],nodeId:h.reason_code,stage:'commit',action:h.action});go('flow')};
const Icon=flow?icons[draft.behavior]:Leaf;
function nav(){return <nav className="bottom-nav" aria-label="主导航">{[['home','此刻',House],['records','我的记录',ClockCounterClockwise],['library','我的方法',Plant]].map(([id,label,I])=>{const N=I as typeof House;return <button key={id as string} className={route===id?'active':''} onClick={()=>go(id as string)}><N size={23} weight={route===id?'fill':'regular'}/><span>{label as string}</span></button>})}</nav>}
function choice(label:React.ReactNode,onClick:()=>void,key?:string){return <button className="choice" onClick={onClick} key={key}><span>{label}</span><ArrowRight size={19}/></button>}
function historyCard(h:RecordItem){const B=icons[h.behavior];return <article className="record" key={h.id}><div className="record-meta"><span><B/> {behaviors.find(b=>b.id===h.behavior)?.name} · {date(h.createdAt)}</span><span className={`status ${h.status}`}>{statusText[h.status]}</span></div><h3>{h.reasonLabel}</h3><p>{h.action.title}</p><div className="record-actions"><button className="text-btn" onClick={()=>setExpanded(expanded===h.id?undefined:h.id)}>{expanded===h.id?'收起过程':'看看这次的过程'} <ArrowUpRight/></button>{h.status==='WAITING'&&<button className="text-btn" onClick={()=>go(`feedback/${h.id}`)}>验证效果 →</button>}</div>{expanded===h.id&&<div className="record-detail"><p>{h.when==='past'?'事后复盘':'当下求助'} · {h.reason_path.join(' → ')}</p><p>这次尝试：{h.action.title} · 第 {h.intervention_version} 版</p>{h.feedback_code&&<p>反馈：{feedbackLabels[h.feedback_code]||h.feedback_code}</p>}{h.parent_record_id&&<p>上次尝试：{history.find(p=>p.id===h.parent_record_id)?.action.title}（{statusText[history.find(p=>p.id===h.parent_record_id)?.status||'WAITING']}）</p>}{history.filter(p=>p.parent_record_id===h.id).map(p=><p key={p.id}>后来调整：{p.action.title} · {statusText[p.status]}</p>)}</div>}</article>}
return <div className="app"><header className="brand"><button onClick={()=>go('home')} className="brand-name"><span className="brand-mark"><Leaf weight="fill"/></span>自律搭子</button></header>{error&&<div role="status" className="notice">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X/></button></div>}
<main ref={top} tabIndex={-1} className={flow?'flow-main':'main'}>
{route==='home'&&<><section className="hero"><div className="hero-copy"><h1>不用一下变得自律。<br/>先从<span>这一次</span>开始。</h1></div><div className="illustration" aria-hidden="true"><div className="illustration-scene"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="spark s1">✦</span><span className="spark s2">✳</span><div className="buddy big"><div className="sprout"><i/><i/></div><div className="eyes"><i/><i/></div><div className="cheek"/></div><div className="buddy small"><div className="eyes"><i/><i/></div></div><div className="ground"/></div></div></section>
{waiting.length>0&&<section className="follow-card"><div className="follow-icon"><ClockCounterClockwise size={26}/></div><div><span className="eyebrow">上次的小尝试 · 待验证{waiting.length>1?`（还有 ${waiting.length} 条）`:''}</span><h2>先看看，那个办法有没有用？</h2><p>{waiting[0].reasonLabel} · {waiting[0].action.title}</p></div><button className="primary" onClick={()=>go(`feedback/${waiting[0].id}`)}>聊聊结果 <ArrowRight/></button></section>}
{draft&&<button className="resume" onClick={()=>go('flow')}>继续刚才的{behaviors.find(b=>b.id===draft.behavior)?.name}小对话 <ArrowRight/></button>}
<section className="scene-section"><div className="section-head"><div><h2>此刻，什么让你有点为难？</h2></div></div><div className="scene-grid">{behaviors.map((b,i)=>{const B=icons[b.id];return <button className={`scene ${b.color} scene-${i}`} aria-label={b.title} key={b.id} onClick={()=>start(b.id)}><span className="scene-icon"><B size={30} weight="duotone"/></span><div><h3>{b.title.includes('，')?<>{b.title.split('，')[0]}，<span className="scene-title-line">{b.title.split('，')[1]}</span></>:b.title}</h3></div><ArrowUpRight className="scene-arrow" size={21}/></button>})}</div><button className="review-entry" onClick={()=>setReview(true)}><ClockCounterClockwise size={22}/><span>已经发生了？<strong> 帮我复盘一下</strong></span><ArrowRight size={20}/></button></section></>}
{flow&&node&&<><div className="flow-top"><button className="icon-btn" aria-label="返回上一步" onClick={back}><ArrowLeft/></button><span><Icon/> {behaviors.find(b=>b.id===draft.behavior)?.name} · {draft.when==='past'?'一起复盘':'现在拉我一把'}</span><button className="icon-btn" aria-label="暂存并退出" onClick={()=>go('home')}><X/></button></div><div className="steps"><span className="selected">找到原因</span><i/><span className={['strategy','commit'].includes(draft.stage)?'selected':''}>试个办法</span><i/><span className={draft.stage==='commit'?'selected':''}>慢慢验证</span></div><section className="question-panel" key={draft.nodeId+draft.stage}>
{node.support?<><div className="question-symbol"><Heart size={32}/></div><h1>{node.title}</h1><p className="lead">{node.support}</p><button className="primary wide" onClick={()=>{setDraft(undefined);go('home')}}>今天先到这里</button></>:node.reason?<>{draft.stage==='reason'&&<><h1>这次更像是……</h1><div className="reason-note"><Leaf size={26}/><h2>{node.reason.label}</h2></div>{draft.parent&&history.find(h=>h.id===draft.parent)?.reason_code!==node.reason.code&&<div className="feedback-summary"><small>上次的判断：{history.find(h=>h.id===draft.parent)?.reasonLabel}</small><p>这次根据你的回答，改为：{node.reason.label}</p></div>}{!draft.noShortcut&&effective.find(s=>s.reason_code===node.reason!.code&&s.behavior===draft.behavior)&&(()=>{const s=effective.find(s=>s.reason_code===node.reason!.code&&s.behavior===draft.behavior)!;return <div className="shortcut"><span className="eyebrow">这个办法曾经帮到过你</span><h3>{s.action.title}</h3><p>这次也是相同的情境吗？</p><button className="primary wide" onClick={()=>patch({action:s.action,stage:'commit'})}>是的，直接照上次做 <ArrowRight/></button><button className="text-btn" onClick={()=>{patch({trail:[],nodeId:draft.behavior,stage:'question',noShortcut:true})}}>今天情况不一样，重新找原因</button></div>})()}<button className="primary wide" onClick={()=>patch({stage:'strategy'})}>嗯，选一个小办法 <ArrowRight/></button><button className="text-btn centered" onClick={back}>不太像，回去看看</button></>}
{draft.stage==='strategy'&&<><h1>{draft.when==='past'?'下次，只试一个小动作。':'这次，只试一个小动作。'}</h1><p className="lead">{node.reason.label}</p><div className="options">{actionList(node.reason.code,draft.behavior,history,draft.parent&&draft.adjustment?adjusted(history.find(h=>h.id===draft.parent)!,draft.adjustment):undefined).map(a=>choice(<><strong>{draft.when==='past'?'下次尝试：':''}{a.title}</strong>{a.version>1&&<small>根据反馈调整 · 第 {a.version} 版</small>}{effective.some(s=>s.action.code===a.code&&s.version===a.version)&&<small>曾经对你有效</small>}</>,()=>patch({action:a,stage:'commit'}),a.code+a.version))}</div>{!actionList(node.reason.code,draft.behavior,history).length&&<p className="lead">这一组办法已经试过了。我们重新找找原因，也可以今天先停在这里。</p>}{methods.some(m=>m.behavior===draft.behavior&&m.reason_code===draft.nodeId&&!effective.some(s=>s.action.code===m.code&&s.version===m.action.version))&&<div className="saved-options"><h2>我创建的方法</h2>{methods.filter(m=>m.behavior===draft.behavior&&m.reason_code===draft.nodeId&&!effective.some(s=>s.action.code===m.code&&s.version===m.action.version)).map(m=>choice(m.action.title,()=>patch({action:m.action,stage:'commit'}),m.code+m.action.version))}</div>}
{customOpen?<form className="custom-form" onSubmit={saveMethod}><label htmlFor="method-title">创建自己的方法</label><textarea id="method-title" autoFocus maxLength={120} required rows={3} placeholder="这次，你想试什么？" value={draft.customText||''} onChange={e=>patch({customText:e.target.value})}/><label htmlFor="method-minutes">计时（可选，分钟）</label><input id="method-minutes" type="number" min={1} max={180} step={1} value={draft.customMinutes||''} onChange={e=>patch({customMinutes:e.target.value})}/>{customError&&<p role="alert" className="form-error">{customError}</p>}<button className="primary wide" type="submit">保存并选择这个方法</button><button className="text-btn centered" type="button" onClick={()=>setCustomOpen(false)}>取消</button></form>:<button className="secondary wide create-method" onClick={()=>setCustomOpen(true)}>都不合适？创建自己的方法</button>}
<button className="text-btn centered" onClick={()=>start(draft.behavior,draft.when,draft.parent)}>重新找原因</button></>}
{draft.stage==='commit'&&draft.action&&<><div className="question-symbol"><Check size={32}/></div><h1>{draft.when==='past'?'给下次，留一个小办法。':'就从这一小步开始。'}</h1><div className="action-note"><span>{draft.when==='past'?'下次遇到时，我会':'这次，我想试试'}</span><h2>{draft.action.title}</h2><p className="action-context">{node.reason.label}</p>{draft.action.minutes&&<span className="time-pill"><Timer/> {draft.action.minutes} 分钟</span>}</div><button className="primary wide" onClick={commit}>好，就试这个 <ArrowRight/></button></>}</>:<><h1>{draft.when==='past'?node.title.replace('现在','当时').replace('你怎么还没睡','当时为什么没睡').replace('今晚','那天晚上'):node.title}</h1>{node.hint&&<p className="lead">{node.hint}</p>}<div className="options">{node.options.map((o,i)=>choice(o.label,()=>choose(o.label,o.to),`${o.to}-${i}`))}</div></>}
</section></>}
{route.startsWith('done/')&&current&&<section className="result-panel"><div className="success-icon"><CheckCircle size={48} weight="duotone"/></div><h1>{current.status==='WAITING'?'已加入我的记录':'验证结果已保存'}</h1><div className="action-note"><h2>{current.action.title}</h2><span className={`status ${current.status}`}>{statusText[current.status]}</span></div>
{current.action.origin==='custom'&&<p className="method-progress">已验证很有效 {allStrategies.find(s=>s.intervention_code===current.intervention_code&&s.version===current.intervention_version)?.success_count||0} 次{(allStrategies.find(s=>s.intervention_code===current.intervention_code&&s.version===current.intervention_version)?.success_count||0)>=3?' · 已加入我的办法':' / 3'}</p>}
{current.status==='WAITING'&&current.action.minutes&&<div className="timer-box">{current.timerEnd?<><span className="timer-digits">{Math.floor(remaining(current.timerEnd,now)/60).toString().padStart(2,'0')}:{(remaining(current.timerEnd,now)%60).toString().padStart(2,'0')}</span><p role="status">{remaining(current.timerEnd,now)>0?'计时中':'时间到了，可以验证效果。'}</p></>:<button className="secondary" onClick={()=>setHistory(prev=>prev.map(h=>h.id===current.id?{...h,timerEnd:Date.now()+h.action.minutes!*60000}:h))}><Timer/> 开始 {current.action.minutes} 分钟计时</button>}</div>}
<button className="primary wide" onClick={()=>go('records')}>查看我的记录 <ArrowRight/></button>
{current.status==='WAITING'?<button className="secondary wide result-secondary" onClick={()=>go(`feedback/${current.id}`)}>我试过了，验证效果</button>:<>{(current.action.origin==='custom'||current.status==='WORKED')&&<button className="secondary wide result-secondary" onClick={()=>reuse(current)}>再试一次</button>}{current.status!=='WORKED'&&<button className="text-btn centered" onClick={()=>go(`adjust/${current.id}`)}>调整这个方法</button>}</>}
<button className="text-btn centered" onClick={()=>go('home')}>回到此刻</button></section>}
{(route.startsWith('feedback/')||route.startsWith('adjust/'))&&current&&<section className="question-panel feedback-panel"><button className="text-btn" onClick={()=>go('home')}><ArrowLeft/> 回到此刻</button><h1>{activeFeedback==='FAILED'?'上次的方法，没有解决真正卡住你的地方。':activeFeedback==='PARTLY_WORKED'?'有帮助的部分留下，卡住的部分再调整。':activeFeedback==='NOT_TRIED'?'没试过，不代表办法没用。':'那个办法，有没有帮到你？'}</h1><div className="feedback-summary"><small>{date(current.createdAt)} · {current.reasonLabel}</small><h3>{current.action.title}</h3></div>{current.status!=='WAITING'&&!route.startsWith('adjust/')?<><p className="lead">这次结果已记录：{statusText[current.status]}。</p><button className="primary" onClick={()=>go('records')}>看看记录</button></>:!activeFeedback?<><div className="options">{(['FAILED','PARTLY_WORKED','WORKED'] as Status[]).map(s=>choice(statusText[s],()=>submitRating(current,s),s))}</div><button className="text-btn centered" onClick={()=>submitRating(current,'NOT_TRIED')}>其实还没试</button></>:<><p className="lead">{activeFeedback==='FAILED'?'发生了什么？这次我们会排除相同的失败版本，再找原因。':activeFeedback==='PARTLY_WORKED'?'具体卡在了哪里？':'是什么让它没能发生？'}</p><div className="options">{(activeFeedback==='NOT_TRIED'?[['effort','当时觉得麻烦'],['forgot','后来忘了'],['unwilling','真到那时就不想做'],['unsuitable','这个方法本来就不适合我']]:activeFeedback==='PARTLY_WORKED'?[['before','开始之前，又拖了很久'],['during','做到了，后来又回去了'],['after','做完这一步，还是没解决'],['different','其他情况更接近，需要重新找原因']]:['sleep','phone'].includes(current.behavior)?[['returned','又拿回来了 / 继续刷了'],['device','开始用电脑或平板'],['different','没有设备，也不想停下来'],['thoughts','一直想着其他事情']]:[['continued','还是重复了原来的行为'],['environment','环境又把我拉回去了'],['different','我发现真正的原因不一样'],['unsolved','做了，但困扰还在']]).map(([code,label])=>choice(label,()=>resolve(current,activeFeedback!,code),code))}</div><button className="text-btn centered" onClick={()=>go(`done/${current.id}`)}>暂时不调整</button></>}</section>}
{route==='records'&&<section className="collection"><h1>我的记录<span className="count">{history.length}</span></h1>{history.length?<div className="timeline">{[...history].reverse().map(historyCard)}</div>:<div className="empty"><ClockCounterClockwise size={44}/><h2>你的故事，从一次小尝试开始。</h2><p>确认一个小行动后，它就会出现在这里。</p><button className="primary" onClick={()=>go('home')}>找一个小办法 <ArrowRight/></button></div>}{history.length>0&&<button className="text-btn danger" onClick={()=>setClear(true)}>清空本地记录</button>}<p className="quiet">记录只保存在当前浏览器，不会上传。清除浏览器数据也会清除这些记录。</p></section>}
{route==='library'&&<section className="collection"><h1>我的方法</h1><div className="method-tabs" role="group" aria-label="方法分类"><button aria-pressed={methodTab==='created'} onClick={()=>setMethodTab('created')}>我创建的</button><button aria-pressed={methodTab==='effective'} onClick={()=>setMethodTab('effective')}>我的办法</button></div>
{methodTab==='created'?<>{methods.length?<><p className="method-rule">累计三次“很有效！”，就会加入我的办法。</p>{[...methods].reverse().map(m=>{const stats=allStrategies.find(s=>s.intervention_code===m.code&&s.version===m.action.version);const pending=waiting.find(h=>h.intervention_code===m.code&&h.intervention_version===m.action.version);return <article className="library-card" key={m.code+m.action.version}><div className="record-meta"><span>{behaviors.find(b=>b.id===m.behavior)?.name}</span><span className="status">{stats?.status==='effective'?'已加入我的办法':`很有效 ${stats?.success_count||0} / 3`}</span></div><h3>{m.action.title}</h3><p>{m.reasonLabel}</p><div className="record-actions"><button className="text-btn" onClick={()=>useMethod(m)}>再试一次 <ArrowRight/></button>{pending&&<button className="text-btn" onClick={()=>go(`feedback/${pending.id}`)}>验证上次效果</button>}</div></article>})}</>:<div className="empty"><Plant size={48}/><h2>还没有自己创建的方法</h2><p>选择方法时，可以写下自己的做法。</p><button className="primary" onClick={()=>go('home')}>从一个场景开始</button></div>}</>:<>{effective.length?behaviors.map(b=>{const list=effective.filter(s=>s.behavior===b.id);return list.length?<section className="strategy-group" key={b.id}><h2>{b.name}</h2>{list.map(s=><article className="library-card" key={s.action.code+s.version}><h3>{s.action.title}</h3><p>{s.reasonLabel} · 很有效 {s.success_count} 次</p><button className="text-btn" onClick={()=>useMethod(s)}>再试一次 <ArrowRight/></button></article>)}</section>:null}):<div className="empty"><Plant size={48}/><h2>等待一个对你有效的办法</h2><p>自建方法累计三次“很有效！”后会出现在这里。</p><button className="primary" onClick={()=>go('records')}>验证我的尝试</button></div>}</>}
</section>}
{!['home','flow','records','library'].includes(route)&&!current&&<div className="empty"><h1>这条记录暂时找不到了。</h1><button className="primary" onClick={()=>go('home')}>回到此刻</button></div>}{route==='flow'&&!draft&&<div className="empty"><h1>从这一次开始。</h1><button className="primary" onClick={()=>go('home')}>选择一个场景</button></div>}
</main>{!flow&&nav()}{(review||clear)&&<div className="modal-backdrop" onClick={()=>{setReview(false);setClear(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){setReview(false);setClear(false)}if(e.key==='Tab'){const items=e.currentTarget.querySelectorAll<HTMLButtonElement>('button');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><button autoFocus className="icon-btn close" aria-label="关闭" onClick={()=>{setReview(false);setClear(false)}}><X/></button><h2 id="modal-title">{clear?'清空这些小尝试？':'已经发生的，也可以成为线索。'}</h2><p>{clear?'这会删除当前浏览器的全部记录、办法和未完成对话，无法撤销。':'先不责怪自己。你想复盘哪件事？'}</p>{clear?<><button className="primary wide" onClick={()=>{try{clearStorage()}catch{}setHistory([]);setMethods([]);setDraft(undefined);setFirstVisit(new Date().toISOString());setClear(false);go('home')}}>确认清空</button><button className="text-btn centered" onClick={()=>setClear(false)}>保留记录</button></>:behaviors.map(b=>choice(b.title,()=>start(b.id,'past'),b.id))}</div></div>}</div>
}
const feedbackLabels:Record<string,string>={worked:'确实帮到了我',before:'开始之前又拖了很久',during:'做到了，后来又回去了',after:'做完后仍有困难',different:'真正的原因不一样',effort:'当时觉得麻烦',forgot:'后来忘了',unwilling:'临场不想执行',unsuitable:'方法不适合我',returned:'又拿回来了 / 继续刷了',device:'改用其他设备',thoughts:'一直想着其他事情',continued:'重复原来的行为',environment:'环境又把我拉回去',unsolved:'困扰仍然存在'};
createRoot(document.getElementById('root')!).render(<App/>);
